fifth increment
volnistii11/URL-shortener pull request #5
Opened 2023-05-08 18:18 UTC by volnistii11

2023-05-12 19:04 UTC, arttet requested changes
Good job!

2023-05-12 19:04 UTC, arttet commented on internal/app/storage/storage.go
> +var URLMap map[string]string
Which rule of `SOLID` did you break?

2023-05-12 19:04 UTC, arttet commented on internal/app/handlers/handler.go
> +	storage.URLMap = map[string]string{}
You shouldn't do it here. Please use `struct` or `function`

2023-05-14 21:49 UTC, volnistii11 commented on internal/app/handlers/handler.go
> +func errorResponse(err string) gin.H {
Sry, what do you mean?)

2023-05-14 22:06 UTC, volnistii11 commented on internal/app/storage/storage.go
> +var URLMap map[string]string
Type inside a var name?

2023-05-16 17:54 UTC, arttet approved these changes
Well done!

2023-05-16 17:54 UTC, arttet commented on internal/app/handlers/handler.go
> +	if err != nil {
Nit: you can reduce this space
```
	if err != nil {
		ctx.JSON(http.StatusBadRequest, errorResponse(err))
                return
	}

        ctx.Header("Location", fullURL)
        ctx.Status(http.StatusTemporaryRedirect)
```

2023-05-21 20:10 UTC, merged